POST http://localhost:1210/api/user/auth/register
Content-Type: application/json

{
    "profilepic": "",
    "birthday": "10-12-2000",
    "gender": "",
    "email": "",
    "fname": "Thành",
    "lname": "Lưu",
    "phone": "+84582199172",
    "password": "test1234",
    "city": "", 
    "district": "" , 
    "ward": "", 
    "street": "",
    "role": "user"
}

###

POST http://localhost:1210/api/user/auth/login
Content-Type: application/json

{
    "phone": "+84582199174",
    "password": "test1234"
}

###

POST http://localhost:2542/api/user/auth/verifycode
Content-Type: application/json

{
    "phone": "+84582199172",
    "code": "585903"
}

###

POST http://localhost:1210/api/user/auth/sendcode
Content-Type: application/json
    
{
    "phone": "+84582199172"
}

###

POST http://localhost:1210/api/user/auth/createuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWUyMTlhMTI4ZGZlYjU1N2M5YWYyZjAiLCJpYXQiOjE2NDIyMDc3Mjd9.f8I-gLJ7thA7nENWCk6UTLONOcyZinqvfXnl3CEXCX8

{
    "account": "61e219a128dfeb557c9af2f0",
    "bloodtype": "AB",
    "height": "1m75",
    "weight": "68kg",
    "pastmedicalhistory": "hehe",
    "drughistory": "",
    "familyhistory": ""
}

### 
GET http://localhost:1210/api/user/61d140313f972b7b9c20434c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWUzNzVkOTk0ZDUxMTBhY2FlNDMwNmMiLCJpYXQiOjE2NDIzMTAyMDF9.7F6OpCdNUTrrBOIe4E26Ne8Syadpor_bK0GQ6t5VDBU

### 
PUT http://localhost:1210/api/user/61d140313f972b7b9c20434c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDI5ODY2MzV9.7al6ae-uolgaS6gTjPeWcsogpM7l093kWlAVp7jtFN0
Content-Type: application/json

{
    "bloodtype": "O",
    "height": "1m50",
    "weight": "90kg",
    "pastmedicalhistory": "chào buổi tối",
    "drughistory": "",
    "familyhistory": ""
}

###
POST http://localhost:1210/api/user/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWNmZmE4MjE5NzM1ODNlYmYyZmMzNDYiLCJpYXQiOjE2NDExNDExNzl9.Y0T5md-_fUvdPgqcvbxRi1uvKIlgqvah0SEbym_9aVQ
Content-Type: application/json

{
    "password": "121000",
    "newpass": "254200"
}

###
POST http://localhost:1210/api/user/auth/resetpassword
Content-Type: application/json

{
    "phonenum": "+84582199174",
    "newpassword": "121000"
}

### 
GET http://localhost:1210/api/user/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWUzNzVkOTk0ZDUxMTBhY2FlNDMwNmMiLCJpYXQiOjE2NDIyOTg2NjZ9.2tROAi6b0FxyX_yT0loEo7X_U5v6p09kQBX02Acu8xM
Content-Type: application/json

### 
PUT http://localhost:1210/api/user/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU0ZjY2NGNhNGQ3MGQ0MTI0OThjYmMiLCJpYXQiOjE2NDIzOTUyMzZ9.gXYQBjwz87A8HsUDPOgnMsOf0nYYei1rh0UWId39ntE
Content-Type: application/json

{
    "profilepic": "https://google.com",
    "fname": "Thanh",
    "lname": "Luu",
    "birthday": "04-25-2000",
    "gender": 2,
    "city": "Hồ Chí Minh",
    "district": "7",
    "ward": "Tân Hưng",
    "street": "TXS"
}

###
GET http://localhost:1210/api/user/
Content-Type: application/json

###
GET http://localhost:1210/api/home/doctor
Content-Type: application/json

###
GET http://localhost:1210/api/home/doctor/61e91b5b9485388e6570363a
Content-Type: application/json

###
GET http://localhost:1210/api/home/docdep/61e915d19485388e65703633
Content-Type: application/json

###
GET http://localhost:1210/api/home/docacc/61e21e9f1d54cf11cc5e2708
Content-Type: application/json

###
GET http://localhost:1210/api/home/department
Content-Type: application/json

###
GET http://localhost:1210/api/user/consultation/viewlistconsult
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDI5MTU4NTd9.h26WnIQiGHMmshJrQCX7Qc_iKzhvIHgWrCBp5JDP2Tc
Content-Type: application/json

###
GET http://localhost:1210/api/user/consultation/viewlistconsult/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDI5MTU4NTd9.h26WnIQiGHMmshJrQCX7Qc_iKzhvIHgWrCBp5JDP2Tc
Content-Type: application/json

###
POST http://localhost:1210/api/user/consultation/createconsult
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI2NDIyMjB9.yefwjXLot1B__RJXvqTwpVlMAEXQAuVzpTd7y13F37s
Content-Type: application/json

{
    "status": 4,
    "symptom": "Lao phổi",
    "dateconsult": "2022-05-05",
    "hour": "30 phút",
    "roomname": "98998",
    "doctor": "61e836d0d0abc69f73c98b00",
    "user": "61d140313f972b7b9c20434c"
}
###
GET http://localhost:1210/api/user/prescription/viewListPrescription
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDc1MDgzOTJ9.ZIKyX54ZT6LZGQohSzrlSvF5nlOTjkDoI7cRrBCAgKs
Content-Type: application/json

###
POST http://localhost:1210/api/user/prescription/createPrescription
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDc1MjE1NDB9.Gh3iAK1lAgct39qK41W5l-RHIntnSMxh9MadCY8thNM
Content-Type: application/json

{
    "consultation": "61ece22958149b526e1ec79a",
    "pname": "Toa thuốc",
    "diagnosis": "Đau nhức xương khớp",
    "note": "Hạn chế vận động",
    "product": "6232e81a4ec426dd1fc4d3e2",
    "quantity": 4,
    "morningrate": "1 viên",
    "noonrate": "1 viên",
    "everate": "1 viên",
    "specdes": "Quy cách sản phẩm"
}
###
PUT http://localhost:1210/api/user/prescription/updatePrescription/623343e694e597fa95a0bc43
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDc1ODg3MDJ9.szYfgNFelk6HTaDWoYNyEbZ47m-cmfOuEk_kcByL7FM
Content-Type: application/json

{
    "consultation": "61ece22958149b526e1ec79a",
    "pname": "Toa thuốc",
    "diagnosis": "Đau",
    "note": "Hạn chế vận động",
    "product": "6232e81a4ec426dd1fc4d3e2",
    "quantity": 4,
    "morningrate": "1 viên",
    "noonrate": "1 viên",
    "everate": "1 viên",
    "specdes": "Quy cách sản phẩm"
}
###
DELETE http://localhost:1210/api/user/prescription/deletePrescription/623343e694e597fa95a0bc43
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDc1ODg3MDJ9.szYfgNFelk6HTaDWoYNyEbZ47m-cmfOuEk_kcByL7FM

###
GET http://localhost:1210/api/user/prescription/searchPrescription/Viêm họng
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWVhMGI3YWNjMDNlNDIyZDU3NDRhOGMiLCJpYXQiOjE2NDc1ODg3MDJ9.szYfgNFelk6HTaDWoYNyEbZ47m-cmfOuEk_kcByL7FM