POST http://localhost:1210/api/user/auth/register
Content-Type: application/json

{
    "fname": "Khanh",
    "lname": "Đinh",
    "phonenum": "0582199179",
    "password": "123456",
    "role": "người dùng"
}

###

POST http://localhost:1210/api/user/auth/login
Content-Type: application/json

{
    "phonenum": "+84582199172",
    "password": "test1234"
}

###

POST http://localhost:1210/api/user/auth/verifycode
Content-Type: application/json

{
    "phonenum": "+84582199172",
    "code": "585903"
}

###

POST http://localhost:1210/api/user/auth/sendcode
Content-Type: application/json
    
{
    "phonenum": "+84582199172"
}

###

POST http://localhost:1210/api/user/auth/createuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWQxM2ZjYmJlZWI5NzJjMTdlNzMyNWIiLCJpYXQiOjE2NDExMDMzMDd9.nDnV_UYQ_xaTHOnwf3RmbYerRFCL1beT2MmUWrpSZLo

{
    "account": "61d13fcbbeeb972c17e7325b",
    "bloodtype": "AB",
    "height": "1m75",
    "weight": "68kg",
    "pastmedicalhistory": "trượt ván",
    "drughistory": "",
    "familyhistory": ""
}

### 
GET http://localhost:1210/api/user/61cffe8dc8d94622b5936c48
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI0MjI0NTB9.iSdYe2mpQElG2fAhBT1UoQnsrQgIC2C1IbckPnitMKQ

### 
PUT http://localhost:1210/api/user/61cffe8dc8d94622b5936c48
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI0MjI0NTB9.iSdYe2mpQElG2fAhBT1UoQnsrQgIC2C1IbckPnitMKQ
Content-Type: application/json

{
    "bloodtype": "O",
    "height": "1m50",
    "weight": "90kg",
    "pastmedicalhistory": "đói quá",
    "drughistory": "",
    "familyhistory": ""
}

###
POST http://localhost:1210/api/user/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWNmZmE4MjE5NzM1ODNlYmYyZmMzNDYiLCJpYXQiOjE2NDExNDExNzl9.Y0T5md-_fUvdPgqcvbxRi1uvKIlgqvah0SEbym_9aVQ
Content-Type: application/json

{
    "password": "121000",
    "newpass": "254200"
}

###
POST http://localhost:1210/api/user/auth/resetpassword
Content-Type: application/json

{
    "phonenum": "+84582199174",
    "newpassword": "121000"
}

### 
GET http://localhost:1210/api/user/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI0MjI0NTB9.iSdYe2mpQElG2fAhBT1UoQnsrQgIC2C1IbckPnitMKQ

### 
PUT http://localhost:1210/api/user/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI0MjI0NTB9.iSdYe2mpQElG2fAhBT1UoQnsrQgIC2C1IbckPnitMKQ
Content-Type: application/json

{
    "profilepic": "https://facebook",
    "fname": "Hải",
    "lname": "Lưu",
    "birthday": "2022-01-31T17:00:00.000+00:00",
    "gender": 1,
    "city": "Hồ Chí Minh",
    "district": "7",
    "ward": "Tân Hưng",
    "street": "TXS"
}

###
GET http://localhost:1210/api/home/doctor
Content-Type: application/json

###
GET http://localhost:1210/api/home/doctor/61e21e991d54cf11cc5e2707
Content-Type: application/json

###
GET http://localhost:1210/api/home/department
Content-Type: application/json

###
GET http://localhost:1210/api/user/consultation/viewlistconsult
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI0MzA5OTl9.-Ffs-DuAHycxL5lCKsDSC4N98gRIX0F5npKXgO_qUMI
Content-Type: application/json

###
POST http://localhost:1210/api/user/consultation/createconsult
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MWU1MWYyZGE2OTVjZmYyYmQ1YzAxMWYiLCJpYXQiOjE2NDI1NTY1MTd9.NKRDRxn7TIC8NzMtULWsl2GicybTDikbNRh7IJnYWM0
Content-Type: application/json

{
    "doctor": "61e0cece97629c08e6644865",
    "user": "61d140313f972b7b9c20434c",
    "status": 1,
    "symptom": "Viêm họng",
    "date": "22-12-2022",
    "hour": "20 phút",
    "ratingcontent": "quá tuyệt vời",
    "roomname": "",
    "ratingstarcontent": 1
}